version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: frontend
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network
networks:
  app-network:
    external: true